[package]
name = "lzo1x"
version = "0.1.0"
edition = "2021"
rust-version = "1.75.0"

[[test]]
name = "test"
harness = false

[profile.bench]
debug = true

[dev-dependencies]
lzo-sys = "0.3.1"
zip = "0.6.6"
